apiVersion: v2
name: clusterjellyfin
description: Kubernetes-deployed Jellyfin with distributed transcoding using rffmpeg and Intel Arc QSV acceleration
type: application
version: 0.1.47
appVersion: "10.9.11"
keywords:
  - jellyfin
  - media
  - transcoding
  - rffmpeg
  - intel-arc
  - qsv
  - postgresql
home: https://github.com/celesrenata/clusterjellyfin
icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-transparent.svg
sources:
  - https://github.com/celesrenata/clusterjellyfin
maintainers:
  - name: celesrenata
