{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clusterjellyfin.fullname" . }}-postgresql-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clusterjellyfin.labels" . | nindent 4 }}
    component: postgresql
type: Opaque
data:
  username: {{ .Values.postgresql.username | default "jellyfin" | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
