{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clusterjellyfin.fullname" . }}-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clusterjellyfin.labels" . | nindent 4 }}
    component: postgresql
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
  username: {{ "jellyfin" | b64enc | quote }}
  database: {{ "jellyfin" | b64enc | quote }}
  host: {{ printf "%s-postgresql" (include "clusterjellyfin.fullname" .) | b64enc | quote }}
  port: {{ "5432" | b64enc | quote }}
{{- else }}
{{- $secret := lookup "v1" "Secret" .Values.namespace .Values.postgresql.external.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clusterjellyfin.fullname" . }}-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clusterjellyfin.labels" . | nindent 4 }}
    component: postgresql
type: Opaque
data:
  host: {{ .Values.postgresql.external.host | b64enc | quote }}
  port: {{ .Values.postgresql.external.port | toString | b64enc | quote }}
  database: {{ .Values.postgresql.external.database | b64enc | quote }}
  username: {{ .Values.postgresql.external.username | b64enc | quote }}
  {{- if $secret }}
  password: {{ index $secret.data "password" | quote }}
  {{- else }}
  password: {{ "password-not-found" | b64enc | quote }}
  {{- end }}
{{- end }}
